{% set name = "imageai" %}
{% set version = "2.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c57922ba2724da522a5ee831df5aa83120ff3222704860aecafba454c727e1c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - h5py
    - matplotlib-base
    - numpy
    - pillow
    - python
    - scipy
    - opencv
    - keras
    - click
    - scikit-learn
    - keras-resnet
    - tensorflow

test:
  imports:
    - imageai
    - imageai.Detection
    - imageai.Detection.Custom
    - imageai.Detection.Custom.utils
    - imageai.Detection.YOLO
    - imageai.Detection.keras_retinanet
    - imageai.Detection.keras_retinanet.backend
    - imageai.Detection.keras_retinanet.bin
    - imageai.Detection.keras_retinanet.callbacks
    - imageai.Detection.keras_retinanet.layers
    - imageai.Detection.keras_retinanet.models
    - imageai.Detection.keras_retinanet.preprocessing
    - imageai.Detection.keras_retinanet.utils
    - imageai.Prediction
    - imageai.Prediction.Custom

about:
  home: https://github.com/OlafenwaMoses/ImageAI
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A python library built to empower developers to build applications and systems  with self-contained Computer Vision capabilities"
  dev_url: https://github.com/OlafenwaMoses/ImageAI

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
